### PR TITLE
Support sorting by multiple columns

### PR DESCRIPTION
**Pull request by sumpygump**
This adds the ability to sort by multiple columns.

I ran into a situation where I wanted to sort things by category and then name, but the original orderBy() only allowed sorting by one column. This update allows to call `orderBy()` multiple times and it will sort by the columns in the order that `orderBy` is called.

```
$result = $db->query()
    ->orderBy('category', 'DESC')
    ->orderBy('name', 'ASC');
```

I added tests to fully test this new feature as well.

### CODE REVIEW

**Comment by timothymarois** [comment]
Nice Job! I Like it. Travis CI failed with php 5.6. Is there any way you could reconfigure to get the test to pass? Just trying to stay backward compatible.

**Comment by sumpygump** [comment]
Yeah, I see it fails in PHP 5.6. I will take a look and see what I can do.

**Comment by sumpygump** [comment]
Update: After looking into this I found the problem was because the test where the data items were sorted by only one `orderBy` call was the failing test. Because of how I was asserting the results of this test, I was expecting the same results each time that the `usort` callback function was returning 0 when the items being tested were equal.

It turns out the problem is a difference in how the sort algorithm works in 5.6 vs 7.x, per the php website:
http://php.net/manual/en/migration70.incompatible.php

> *Sort order of equal elements*
> The internal sorting algorithm has been improved, what may result in different sort order of elements, which compare as equal, than before.
> 
> Note:
> Don't rely on the order of elements which compare as equal; it might change anytime.

Based on this I will make an update to the test to account for this. The good news is the core functionality of the multiple orderBys is not something that is using PHP 7.x features only.

**Comment by timothymarois** [comment]
@sumpygump This looks good. Thanks again for looking into it. I will merge this into the next update.

**Pull request merged**
